"""Equivalence tests pinning the converted v2.4 ONNX models to litert's output.

The app converts BirdNET v2.4 from upstream's SavedModel rather than downloading
a vendor ONNX export, and it converts per platform during the build. Nothing
guarantees tf2onnx emits a byte-identical graph on macOS, Windows and Linux, so
byte comparison is the wrong gate. What has to hold is that every platform's
converted model reproduces the numbers the previous ai-edge-litert build
produced, because campaigns analysed across releases land in one time series.

tests/data/birdnet_2_4_reference.npz holds that reference, captured from the
TFLite model by scripts/make_birdnet_2_4_reference.py before litert was dropped.
It cannot be regenerated by the app any more, which is the point: it is a fixed
record of the behaviour being preserved.

Assertions are in confidence space rather than logit space. The logits are an
implementation detail, and what reaches the CSV is sigmoid(logit). Because
d(sigmoid)/d(logit) is at most 0.25, a logit difference shrinks by at least 4x
on the way to the number a user reads.

The tests that load a 73 MB model are marked slow. CI runs the slow suite on
all four platforms with BIRDNET_APP_DATA pointed at the prewarmed cache. The
pickling guard is deliberately not marked, because it is cheap and guards a
failure mode that only shows up under the multiprocessing pipeline.
"""

from __future__ import annotations

import pickle
from pathlib import Path

import numpy as np
import pytest

from pam_analyzer.infrastructure import birdnet_2_4_onnx as onnx_v2_4

REFERENCE = Path(__file__).parent.parent / "data" / "birdnet_2_4_reference.npz"

# Agreement required on the confidence a detection row carries. Measured drift
# on the reference platform is 2.1e-06 for the acoustic model and 3.0e-07 for
# the geo one, so this leaves roughly 48x headroom for a slower BLAS or a
# different onnxruntime build elsewhere. It is deliberately not tightened to
# match: the detection-set tests below are the sensitive gate, and this one is
# meant to survive platform variation rather than measure it.
CONFIDENCE_TOLERANCE = 1e-4

# Thresholds worth pinning: the app's default, plus two lower ones that admit
# many more classes and so give the comparison far more chances to disagree.
DETECTION_THRESHOLDS = (0.25, 0.1, 0.01)

# What TaxonomyServices.region_species_scientific passes to the geo model.
GEO_THRESHOLD = 0.03


def _sigmoid(x: np.ndarray) -> np.ndarray:
    return 1.0 / (1.0 + np.exp(-x))


@pytest.fixture(scope="module")
def reference() -> dict[str, np.ndarray]:
    if not REFERENCE.is_file():
        pytest.fail(f"missing reference fixture {REFERENCE}")
    with np.load(REFERENCE) as data:
        return {k: data[k] for k in data.files}


def _load_backend(kind: str):  # noqa: ANN202
    """Instantiate one of our backends the way BackendLoader does."""
    backend_type = (
        onnx_v2_4.AcousticOnnxBackendFP32V2_4 if kind == "acoustic" else onnx_v2_4.GeoOnnxBackendFP32V2_4
    )
    backend = backend_type(
        model_path=onnx_v2_4.model_path(kind),
        device_name="CPU",
        half_precision=False,
    )
    backend.load()
    return backend


@pytest.fixture(scope="module")
def acoustic():  # noqa: ANN201
    return _load_backend("acoustic")


@pytest.fixture(scope="module")
def geo():  # noqa: ANN201
    return _load_backend("geo")


def _predict(backend, x: np.ndarray) -> np.ndarray:
    return backend.copy_from_device(backend.predict(backend.copy_to_device(x)))


@pytest.mark.slow
def test_acoustic_confidences_match_litert(acoustic, reference) -> None:
    """The number written to the CSV is unchanged by the move to ONNX.

    This is the assertion the whole conversion exists to satisfy: a campaign
    re-analysed on the ONNX build has to produce the confidences the litert
    build produced for the same audio.
    """
    got = _predict(acoustic, reference["audio"])
    assert got.shape == reference["acoustic_logits"].shape

    delta = np.abs(_sigmoid(got) - _sigmoid(reference["acoustic_logits"]))
    assert delta.max() < CONFIDENCE_TOLERANCE, f"max confidence drift {delta.max():.3e}"


@pytest.mark.slow
@pytest.mark.parametrize("threshold", DETECTION_THRESHOLDS)
def test_acoustic_detection_sets_match_litert(acoustic, reference, threshold: float) -> None:
    """Identical rows survive the confidence threshold, not merely similar scores.

    A drift too small to fail the tolerance above could still move one class
    across the threshold and add or drop a detection row. Comparing the sets
    catches that directly.
    """
    got = _sigmoid(_predict(acoustic, reference["audio"]))
    expected = _sigmoid(reference["acoustic_logits"])

    got_hits = set(np.flatnonzero(got[0] >= threshold).tolist())
    expected_hits = set(np.flatnonzero(expected[0] >= threshold).tolist())
    assert got_hits == expected_hits


@pytest.mark.slow
def test_acoustic_inference_is_deterministic(acoustic, reference) -> None:
    """Two runs of one input agree bit for bit.

    The SavedModel carries dropout and augmentation nodes. They should be
    unreachable in the inference signature, but a conversion that left one live
    would make every analysis irreproducible, which is worth an explicit check
    rather than an assumption.
    """
    first = _predict(acoustic, reference["audio"])
    second = _predict(acoustic, reference["audio"])
    assert np.array_equal(first, second)


@pytest.mark.slow
def test_acoustic_batching_does_not_change_scores(acoustic, reference) -> None:
    """A window scores the same whether analysed alone or inside a batch.

    The runner opens its session with batch_size=8 while the reference is a
    single window, so the batch axis has to be genuinely dynamic. The TFLite
    graph it replaced was pinned to batch 1 and resized by the interpreter,
    which ONNX has no equivalent for.
    """
    single = _predict(acoustic, reference["audio"])
    batched = _predict(acoustic, np.repeat(reference["audio"], 4, axis=0))

    assert batched.shape[0] == 4
    delta = np.abs(_sigmoid(batched) - _sigmoid(single))
    assert delta.max() < CONFIDENCE_TOLERANCE, f"batching moved confidences by {delta.max():.3e}"


@pytest.mark.slow
def test_geo_scores_match_litert(geo, reference) -> None:
    """The geo model converted too, so the species filter is unchanged."""
    got = _predict(geo, reference["geo_inputs"])
    assert got.shape == reference["geo_scores"].shape

    delta = np.abs(got - reference["geo_scores"])
    assert delta.max() < CONFIDENCE_TOLERANCE, f"max geo drift {delta.max():.3e}"


@pytest.mark.slow
def test_geo_species_sets_match_litert(geo, reference) -> None:
    """The allow-list at each reference site is exactly the litert one.

    The geo model gates which detections survive, so a difference here would
    silently change a campaign's results even with the acoustic model matching.
    """
    got = _predict(geo, reference["geo_inputs"])
    for row, (mine, theirs) in enumerate(zip(got, reference["geo_scores"], strict=True)):
        assert set(np.flatnonzero(mine >= GEO_THRESHOLD).tolist()) == set(
            np.flatnonzero(theirs >= GEO_THRESHOLD).tolist()
        ), f"geo species set differs at reference site {row}"


@pytest.mark.parametrize("backend_type", [onnx_v2_4.AcousticOnnxBackendFP32V2_4, onnx_v2_4.GeoOnnxBackendFP32V2_4])
def test_backend_types_are_picklable(backend_type) -> None:
    """The inference pipeline pickles the backend class to reach its workers.

    predict_session spawns worker processes, and each receives the backend
    type by reference. Building these classes inside a function made them
    local objects, which pickle cannot address, so every analysis died at
    startup while in-process tests kept passing. Pickling them here catches
    that without paying for a full run.
    """
    assert pickle.loads(pickle.dumps(backend_type)) is backend_type
